FROM ghcr.io/linuxserver/baseimage-ubuntu:noble AS builder

# env variables
ARG DEBIAN_FRONTEND="noninteractive"

# install build packages
RUN \
    apt-get update && \
    apt-get install -y --no-install-recommends \
       build-essential \
       git \
       qt6-tools-dev \
       qt6-base-dev-tools \
       qmake6 \
       libqt6core5compat6-dev \
       libavif-dev \
       libjxl-dev \
       qt6-declarative-dev && \
    ldconfig

# copy the local repository to the image
COPY . /yacreader

# build and run the test
RUN cd /yacreader/tests/image_format_test && \
    qmake6 image_format_test.pro && \
    make && \
    ./image_format_test
